[features]
seeds = false
skip-lint = false
[programs.localnet]
spok = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/lorenzo/.config/solana/id.json"

[scripts]
test = "yarn run jest --preset ts-jest"
